### ISSUE TITLE
macOS 10.14 required?

### ISSUE THREAD

**Issue by ben-richardson** [kristofa/bookmarker_for_pinboard#11]
I'm stuck on 10.13.6 for the time being. Is 10.14 a requirement? Mac App Store claims so. Thx

**Comment by kristofa** [comment]
@ben-richardson I don't remember setting a specific macOS version requirement. It might have been set by default because I develop on 10.14. I'll try to find out if it can be changed.

**Comment by kristofa** [comment]
@ben-richardson I found that I didn't specify the 'Deployment Target' and that meant it defaults to the macOS version I'm running, 10.14. I'll try updating it to 10.12 for the next release. I'll try to build a new release next weekend.

**Comment by ben-richardson** [comment]
Much appreciated!

**Comment by kristofa** [comment]
@ben-richardson I update the deployment target to 10.12 and submitted a new version (1.3) for review to the App Store. I hope it wil become available in the next few days.
