### ISSUE TITLE
Installs, but does not appear in Safari > Preferences > Extensions under macOS 10.13.6

### ISSUE THREAD

**Issue by ben-richardson** [kristofa/bookmarker_for_pinboard#12]
Many thanks for the updated deployment!

I have installed successfully via the App Store on macOS 10.13.6, Safari 12.1 (13607.1.40.1.5).

"bookmarker for pinboard" launches as expected, and lets me set the API token (very nice, clean work, BTW).

But the "Open in Safari Extensions Preferences…" button does nothing when clicked. 

And the extension does not appear in Safari > Preferences > Extensions.

I have tried a reboot just in case. No change.

Please advise any troubleshooting steps I can take, or bug reporting information I can provide. 

I am very excited for this Extension to come to Safari 12, and would love to help in any way I can.

**Comment by kristofa** [comment]
Thanks for reporting. I haven't encountered this before (I have the app installed on 2 MacBooks, both on 10.14) and didn't get any other reports from other users so far. 

Could you check the `Console.app` (installed by default on macOs) and find out if you see any suspicious Safari logs after starting Safari or after opening the Preferences -> Extensions tab?

**Comment by kristofa** [comment]
@ben-richardson I found out that I only updated the target to 10.12 for the main app and not the extension. I fixed this now and the fix is part of a new version (1.4) that I submitted for review to the App Store.

I would encourage you to try this version once it is available. Let me know if it worked for you or not.

**Comment by kristofa** [comment]
1.4 is in the app store for some time now. Closing issue. Can be reopened if it needed.
