### ISSUE TITLE
Reproducible crashes on saving a bookmark

### ISSUE THREAD

**Issue by mfessler** [kristofa/bookmarker_for_pinboard#15]
I can routinely cause a crash by saving a bookmark. (The bookmark does get successfully saved.) This is an a 2015 13" Retina MBP running Mojave (10.14.5) in clamshell mode. 

Console log reveals:
default	00:16:07.849379 -0400	bookmarker for pinboard Extension	*** Assertion failure in -[bookmarker_for_pinboard_Extension.SafariExtensionViewController dismissViewController:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1671.50.111/Controllers/NSViewController.m:858

error	00:16:07.850187 -0400	bookmarker for pinboard Extension	An uncaught exception was raised

Attaching crashlog.

[bookmarker for pinboard Extension_2019-06-12-001609_Mycroft.crash.txt](https://github.com/kristofa/bookmarker_for_pinboard/files/3279552/bookmarker.for.pinboard.Extension_2019-06-12-001609_Mycroft.crash.txt)

**Comment by kristofa** [comment]
Thanks for reporting @mfessler! 
I noticed I have the same assertion failure in Console. The crash isn't noticeable in Safari and bookmarks are indeed saved as expected. That's why I hadn't noticed this before.  The error has to do with closing the popover window. I'll try to find out how I can prevent this.

**Comment by mfessler** [comment]
Interesting - I’m  getting a model crash notification dialog each time. 
![Screen Shot 2019-06-13 at 12 33 55 PM](https://user-images.githubusercontent.com/876795/59458911-7c129600-8de9-11e9-87c0-d348a283f06c.png)

**Comment by kristofa** [comment]
@mfessler That's bad. I definitely don't get this dialog, I only get the message in Console. 

However it looks like I was able to fix it locally. I don't get the 'Assertion failure' in Console anymore. 
It seems like I closed the popover the wrong way. I'll prepare a new release soon.

**Comment by kristofa** [comment]
@mfessler A new version: 1.5 build 10 is submitted to the App Store for review. I expect it to become available soon. If this version doesn't get rid of the error, reopen the issue. Thanks again for reporting!
