### ISSUE TITLE
Error message truncated in modal

### ISSUE THREAD

**Issue by ckuhl** [kristofa/bookmarker_for_pinboard#16]
On saving a page, the extension encountered an error.

However, the error message was truncated, and so I couldn't read the reason.

**Comment by kristofa** [comment]
Thanks for reporting. I’ll have a look in the next few weeks. I assume this was a temporary error that got resolved after retrying?

**Comment by ckuhl** [comment]
Yep, when I tried again it went through fine! So less of a functionality problem and more of a UI one.

**Comment by kristofa** [comment]
I submitted a new version to the App Store (v1.6) which should become available in the next few days and which fixes the issue with truncating the status/error message.  If the error message is too long there will be a scroll bar now.
