### ISSUE TITLE
Check if page has already been bookmarked and populate existing data

### ISSUE THREAD

**Issue by gingerbeardman** [kristofa/bookmarker_for_pinboard#18]
Often I want to edit an entry in my Pinboard. 
I do this by re-adding an existing bookmark and editing the existing info.

(examples using Shiori)

http://www.koitsu.com/DB/SearchResults.asp

This is the screen I get when I add for the first time:
![Screen shot 2019-08-06 at 00 39 13](https://user-images.githubusercontent.com/49612/62501432-ceb57080-b7e2-11e9-9626-74c13b8ef11c.png)

I then add any information and press Done.

To edit I do a second add.

I see this information:
![Screen shot 2019-08-06 at 00 38 21](https://user-images.githubusercontent.com/49612/62501373-88601180-b7e2-11e9-933e-ba5d9ed8684c.png)

I then edit the information and press Done.

This is not currently possible in bookmarker, it gives you a bare "first time" window every time.

**One more thing**

It would also be good to get a timestamp on when the page was first added to Pinboard. So I could see when it was first added. (An older Safari Extension [Pinbar](https://www.chipwreck.de/blog/software/safari-pinboard-extension/) did this as it just launched the pinboard website)

**Comment by kristofa** [comment]
Thanks for the suggestion @gingerbeardman. I like it. 
The pinboard api supports querying existing entries based on URL.
The documentation is not clear if the `v1/posts/add` API does support updating existing entries but I'll try to give it a try soon.

**Comment by kristofa** [comment]
@gingerbeardman I implemented this request and will try to submit a new version to the App Store during the weekend.

**Comment by kristofa** [comment]
This is what you'll get when you're adding a page link which pinboard already knows about:

<img width="335" alt="Screenshot 2019-10-03 at 14 24 09" src="https://user-images.githubusercontent.com/2221492/66126414-a6cb6900-e5e9-11e9-8545-cdf5e4c8d3ff.png">

Any earlier submitted properties get populated. When you edit the properties and press 'Add' the existing pinboard entry will be updated.

**Comment by gingerbeardman** [comment]
Awesome! Thank you.

Even after many years of open source and GitHub it's such a rush seeing my feature suggestions added to great software. Cheers!

**Comment by apas** [comment]
Looks nice. Couple low priority improvements: change text to “URL already bookmarked, updated existing entry.” (or something similar) and put the “Initially added…” in a new line with a more appropriate time format (eg. just “Initially added on Month Day, Year.”)

**Comment by gingerbeardman** [comment]
Friendly date style would be good, especially for "today" or "yesterday".

@apas maybe "updating existing bookmark" because no changes are saved until "Add bookmark" is clicked.

Which makes me think the button could change to "Update bookmark" in this instance.

**Comment by gingerbeardman** [comment]
Actual web pinboard is a good model to follow:

- just now (within the last hour?)
- hours ago (up to 24 hours)
- yesterday (date is yesterday)
- days ago (up to ~30 days)
- weeks ago (up to 12 weeks)
- july 2019 (over 12 weeks)

and it has an option to delete the bookmark just in case you added it in error.

![Screen shot 2019-10-03 at 16 26 03](https://user-images.githubusercontent.com/49612/66141208-3e858300-e5fb-11e9-85a3-81da9008ecfb.png)
![Screen shot 2019-10-03 at 16 28 33](https://user-images.githubusercontent.com/49612/66141213-3e858300-e5fb-11e9-8214-e66b09692a2f.png)
![Screen shot 2019-10-03 at 16 26 26](https://user-images.githubusercontent.com/49612/66141820-44c82f00-e5fc-11e9-8e70-a55cf18d1554.png)
![Screen shot 2019-10-03 at 16 27 39](https://user-images.githubusercontent.com/49612/66141212-3e858300-e5fb-11e9-840b-963878a1bbfa.png)
![Screen shot 2019-10-03 at 16 37 27](https://user-images.githubusercontent.com/49612/66141781-2b26e780-e5fc-11e9-81ba-95cc9e8f4549.png)
![Screen shot 2019-10-03 at 16 37 18](https://user-images.githubusercontent.com/49612/66141780-2b26e780-e5fc-11e9-96cf-dc11578552c1.png)

**Comment by kristofa** [comment]
Thanks both for the suggestions! I'll update the text for sure before releasing. Current proposal:

```
URL already bookmarked, updating existing entry.
Initially added 2 weeks ago.
```

Where '2 weeks ago' can vary depending on how long ago the link was added. Could be expressed as "just now" or in hours, days, weeks, month + year.

I don't think I'll add the option to delete as part of this release.

**Comment by kristofa** [comment]
Changes implemented and submitted to the App Store for review (v1.7). It should hopefully become available for you to install in the next days.

**Comment by gingerbeardman** [comment]
It's live! Thanks
