### ISSUE TITLE
Save bookmark with keyboard while in Title or URL fields

### ISSUE THREAD

**Issue by roosterboy** [kristofa/bookmarker_for_pinboard#19]
The fix for Issue #10 allows us to trigger saving a bookmark using the keyboard but restricts it to the Description and Tags field. It should apply to the Title and URL fields as well. If a user edits those fields they then have to tab to Description or Tags to hit Return and save and they shouldn't have to do that.

**Comment by kristofa** [comment]
Thanks for reporting. Makes sense. 
Should also be easy to fix. I'll try to get this out soon.

**Comment by kristofa** [comment]
This is implemented and will be part of next release.
