### ISSUE TITLE
Poor legibility of status message

### ISSUE THREAD

**Issue by gingerbeardman** [kristofa/bookmarker_for_pinboard#22]
Blue on white is not good when using dark mode.

(colours should be specified as named system colours to work in both light/dark modes)

![Screen shot 2019-10-27 at 23 30 02](https://user-images.githubusercontent.com/49612/67643668-c5373280-f911-11e9-9227-bb832ab3873c.png)

**Comment by kristofa** [comment]
Thanks for reporting @gingerbeardman. I'll look for documentation about better usage of colours.

**Comment by gingerbeardman** [comment]
Ref:
https://developer.apple.com/documentation/appkit/supporting_dark_mode_in_your_interface/

**Comment by gingerbeardman** [comment]
I looked at doing this and you are already using the correct way of specifying colours. So no real work to do!

The problem is that the blue is not legible depending on the colours of the underlying web page.

Examples:

- ![Screen shot 2019-11-03 at 13 19 01](https://user-images.githubusercontent.com/49612/68085791-a3234000-fe3c-11e9-9777-6542a54faf5e.png)

- ![Screen shot 2019-11-03 at 13 19 29](https://user-images.githubusercontent.com/49612/68085792-a3234000-fe3c-11e9-9edd-d29b0169dd17.png)

So, I would perhaps recommend white for the success message?

**Comment by kristofa** [comment]
Makes sense to change colour. I'll look into it soon.

**Comment by kristofa** [comment]
I did some testing and found that `systemGray` worked quite well with different background colours and both in light as dark mode. I changed the colour and have planned to make a release latest by end of the week.

**Comment by gingerbeardman** [comment]
Thanks!

**Comment by kristofa** [comment]
Update is submitted to the App Store, version 1.9
