### ISSUE TITLE
Add default value for "Read Later" checkbox

### ISSUE THREAD

**Issue by andrewcrook** [kristofa/bookmarker_for_pinboard#23]
It would be really useful to have a default setting for the "Read Later" checkbox so that every bookmark can go into the unread list to be processed later.

**Comment by kristofa** [comment]
@andrewcrook this is already possible. If you open the application "bookmarker for pinboard.app", the application you used to set the API token, you can select default values for `Read Later`and `Private`. See attached screenshot:

<img width="833" alt="Screenshot 2019-11-25 at 20 28 31" src="https://user-images.githubusercontent.com/2221492/69571580-9ff61c80-0fc2-11ea-9084-64121659725a.png">

If you select "Yes" for "Read Later" the Read Later checkbox will be automatically checked when adding a new bookmark. Same for the "Private" setting.
