### ISSUE TITLE
Errors when trying to add bookmark

### ISSUE THREAD

**Issue by aelmeleegy** [kristofa/bookmarker_for_pinboard#28]
I receive both of these issues when I try to add a bookmark. 

The following one appears just after the popover is clicked: 
`When retrieving previously saved bookmark: Got an error when invoking request to api.pinboard.in: The request timed out.`

Then, the following error appears when I click Add Bookmark:
`When adding or updating bookmark: Got an error when invoking request to api.pinboard.in: The request timed out.`

**Comment by kristofa** [comment]
Thanks for reporting @aelmeleegy. 

I've run into these errors as well lately. They occur when the pinboard API doesn't respond within 3 seconds when retrieving tags or when looking up if the URL was already saved before, or within 2 seconds when trying to save or update a bookmark.

I'm not aware of any documented service level objectives related to latency for the pinboard API so I chose these numbers arbitrary.  I'll ask in the pinboard forum. It is probably a good idea to relax the timeout settings even more to for example 5 seconds. I'll update this thread with next steps.

**Comment by kristofa** [comment]
From where in the world (US, EU, Asia,...) are you using the extension?

**Comment by aelmeleegy** [comment]
@kristofa Thank you for following up!

I am using in Egypt. Do you think it might be a latency issue connected to the region?

**Comment by kristofa** [comment]
I think the pinboard servers are at the west coast of the US so there will be some additional latency but I don't think this is the main issue.  

I think that the current timeout of 2 or 3 seconds is probably too optimistic and the pinboard API is sometimes slower to respond. I'm running a test version with a timeout of 5 seconds now and I haven't had the timeout error so far. I'll run it for a little longer and I'll submit a new release in the coming weeks if it keeps on working as expected.

**Comment by kristofa** [comment]
@aelmeleegy I made a new release, v1.11 which should become available in the app store in the next days, which increases the timeout setting. This should make it less likely to get these errors. Feel free to re-open the issue if it doesn't fix it for you.

**Comment by kristofa** [comment]
@aelmeleegy The new version, v1.11 is now available in the App Store.

**Comment by bastionJersey** [comment]
I am also getting both those errors. It goes through eventually, but there doesn't seem to be a confirmation of when the bookmark is saved so I have to check on the website. I am based in the UK and running version 1.11. On MacOS 10.13.6 if that helps at all. Not sure there is anything you can do if it's the API but just updating to let you know it's still going on, at least for me.

**Comment by kristofa** [comment]
@bastionJersey Thanks for reporting. I had the same issue yesterday. It seems to be better this morning for me.
Pinboard is facing issues with its API which is causing these errors. See [this tweet from a week ago](https://twitter.com/Pinboard/status/1355662344039358470).
