### ISSUE TITLE
Add keyboard shortcut support for opening the popover

### ISSUE THREAD

**Issue by kristofa** [kristofa/bookmarker_for_pinboard#3]
Suggested by @apas :

Support a keyboard shortcut for opening the popover window. This will make it faster to open the window instead of having to use a mouse or touchpad to navigate to the toolbar button.

**Comment by apas** [comment]
For reference, the Instapaper and 1Password extensions still support keyboard shortcuts.

**Comment by apas** [comment]
I also suggest the ability for the user to customize the keyboard shortcut from a set of predefined options. The previous Pinboard extension supported various combinations based on actions. For instance the two I remember and used the most:

* [A]dd bookmark with <kbd>opt</kbd> + <kbd>A</kbd> (or <kbd>opt</kbd> + <kbd>Shift</kbd>, etc)
* Show [P]inboard homepage with <kbd>opt</kbd> + <kbd>P</kbd>

**Comment by kristofa** [comment]
See also #10

**Comment by kristofa** [comment]
There is useful information about this issue provided in #10 as I mistakenly saw #3 and #10 as duplicate which they are clearly not.

I submitted a question in the Apple Developer forum (see [here](https://forums.developer.apple.com/thread/115651) if you have access). An Apple staff member replied saying that there is no supported configuration option for assigning keyboard shortcuts for the new Safari App Extensions. It could probably work by injecting a script in each webpage which reacts to keyboard shortcuts (similar as the links @apas shared in #10). I might try that but they also suggested to submit a bug report to ask for improving support for keyboard shortcuts which I did (see [here](https://bugreport.apple.com/web/?problemID=49877009) if you have access).

**Comment by apas** [comment]
LGTM. I think the JS injection is a good compromise if it's doable.

**Comment by kristofa** [comment]
I tried implementing this in #14 but it looks like the Safari App Extension API doesn't give me the access I need to open the popover window. I'll get back to the Apple Developer Forum thread for  feedback.

**Comment by kristofa** [comment]
I updated the [Apple Developer Forum thread](https://forums.developer.apple.com/thread/115651) with my new question.

**Comment by kristofa** [comment]
@apas I got the keyboard support working thanks to an update to the Apple Developer Forum question.  Version 1.6 should become available through the App Store in the next few days and it supports opening the popover using ctrl + alt + a.

**Comment by apas** [comment]
Looks good, just tried it! One future suggestion: is it possible to customize the key combination?

**Comment by kristofa** [comment]
That's a good suggestion @apas
Can you create a new issue with label enhancement? Thanks.

**Comment by apas** [comment]
@kristofa done; I'm afraid I'm not able to add the label myself due to repo rights.
