### ISSUE TITLE
Management like Cloudmark? 

### ISSUE THREAD

**Issue by Caf** [kristofa/bookmarker_for_pinboard#4]
I know I'm about to ask for something quite hard to do buuuut... I'm still sad about the "death" of CloudMark (and so many cool extensions the same dev made). Any chance to have an extended version which displays / offers search for our bookmarks? Damn I wish I could code. ;) Anyway, awesome work here, thanks for this tool!

**Comment by kristofa** [comment]
Thank you. Also thanks for the suggestion but it is more useful to create separate more targeted feature requests. If others indicate wanting the same features and there is time to work on it it might happen :)  Closing this one.
