### ISSUE TITLE
Update API Token button doesn't accept the correct token

### ISSUE THREAD

**Issue by roosterboy** [kristofa/bookmarker_for_pinboard#5]
I followed the instructions from the wiki and when I clicked the Update API Token button, I got a message that says: "Invalid API token format. Expecting username:TOKEN"

I copied the token exactly as it appeared at https://pinboard.in/settings/password

I figured out how to fix it when I noticed that "TOKEN" was all caps in the error message. When I changed the token provided to me by Pinboard—which was a mix of lowercase letters and numbers—to uppercase, it worked.

The application should accept the API token in the format provided by Pinboard.

**Comment by syrabo** [comment]
I have the same

**Comment by kristofa** [comment]
Thanks for letting me know both @roosterboy and @syrabo. I'll update the format check soon.

**Comment by kristofa** [comment]
I submitted a new version (1.2) which includes a fix for this bug to the App Store for review. I expect it to become available in the next days. The new version also allows lower case characters in API tokens values.
