### ISSUE TITLE
Add tag autocomplete/suggestions

### ISSUE THREAD

**Issue by apas** [kristofa/bookmarker_for_pinboard#6]
When typing the description and tags of a new bookmark it would be useful, if possible, to autocomplete a tag based on the users' existing tags.

For instance, a user would type `pro` and `programming` and `productivity` would appear either as a dropdown or inside the text field. The user could press `TAB` to autocomplete the rest of the word or navigate with the arrow keys and select the tag.

**Comment by apas** [comment]
Follow-up: alternatively, if the above is not possible, another approach would be to display the n most used tags of the user and have them click on one (or multiple) to add.

**Comment by kristofa** [comment]
Some more alternatives:
   * pinboard supports [an api call](https://pinboard.in/api/#posts_suggest) to get a list of popular (tags other people used for the same URL) or recommended tags (from the user's own tags). We could integrate with these to prefill suggested tags.
   * some web pages use the [html meta tag](https://www.w3schools.com/tags/tag_meta.asp) standard to suggest keywords. We could get these keywords if defined from the page and use them as suggested tags.

**Comment by kristofa** [comment]
I'll try to list the options:

   1. when a user starts typing a tag, autocomplete it based on the users' existing tags.
   2. alternative to 1, show most used tags and let user select them by clicking on them
   3. pinboard supports an api call to get a list of popular (tags other people used for the same URL) or recommended tags (from the user's own tags). We could integrate with these to prefill suggested tags. We could allow the user to configure which option they prefer: popular or recommended.
   4. some web pages use the html meta tag standard to suggest keywords. We could get these keywords if defined from the page and use them as suggested tags.

Implementing 3. would be the least work. I would be inclined to start with this and iterate if it is not found useful.

**Comment by apas** [comment]
Good ideas. I think autocomplete might be hard both in technical as well as UX terms in the popup. Thus, fetching popular and/or recommended tags, pre-filling, and letting the user click to select some is the best option. (Users, of course, should also be able to type their own tag like now.) The option between popular or recommended is nice.

**Comment by gingerbeardman** [comment]
I currently use [Shiori](https://aki-null.net/shiori/) (native macOS app rather than Safari App Extension) which auto-completes from my own tags when I type. No mouse pick.

I'd prefer to move to an extension so this feature in yours would be great!

**Comment by kristofa** [comment]
Thanks for the feedback @gingerbeardman. If I find some time in next few weeks I might give it a try.

**Comment by kristofa** [comment]
From the options I listed above I looked into number 3 but found out that the pinboard api to get popular (from other people) or recommended tags (from yourself) isn't very useful. As 'recommended' tags it only proposes the tags you used previously when saving the URL.  For popular tags it missed a lot of URL's I saved before and it that case it proposes a default list which didn't make sense. 

So I'll limit the options to the following:

   1. when a user starts typing a tag, autocomplete it based on the users' existing tags.
   2. alternative to 1, show most used tags and let user select them by clicking on them
   3. some web pages use the html meta tag standard to suggest keywords. We could get these keywords if defined from the page and use them as suggested tags.

**Comment by kristofa** [comment]
For all those interested, @apas @gingerbeardman and probably others, I just submitted version 1.10 to the App Store for review which implements tags autocomplete / suggestions.  I described the new functionality as following when submitting to the App Store:

- Tag suggestions / auto-complete: When you start typing your tags you will get tag suggestions based on the tags you used before. You can use the down arrow key to go through the tag suggestion list and the right arrow key to select the tag and to add it to the tags textfield.

What I like about the implementation is that the tags you used the most will appear first in the dropdown list.

I expect this version to become available in the App Store by the beginning of next week.

**Comment by gingerbeardman** [comment]
Thanks! I've been watching this issue. I'll check out the new version and report back.

**Comment by apas** [comment]
Fantastic. Installed new version, works great!

**Comment by gingerbeardman** [comment]
~~I've installed the new version but am not getting any tag suggestions at all?~~

toggling the extension off/on a couple of times has sorted it, thanks!
