### ISSUE TITLE
Default "Private" setting doesn't show in popover

### ISSUE THREAD

**Issue by roosterboy** [kristofa/bookmarker_for_pinboard#8]
Even when the `Default "Private"` setting is set in the app, the checkbox in the popover window in Safari isn't checked.

<img width="833" alt="Screen Shot 2019-03-09 at 13 56 43" src="https://user-images.githubusercontent.com/5996293/54077873-75690580-4273-11e9-9e8b-4b5ac793f97a.png">
<img width="345" alt="Screen Shot 2019-03-09 at 13 57 06" src="https://user-images.githubusercontent.com/5996293/54077874-75690580-4273-11e9-811b-b76cf13b638b.png">

I've tried various combinations of setting/unsetting the setting in the app and deactivating/reactivating the extension in Safari to see if that made it work, to no avail.

(Also, the setting in the app should really be a checkbox rather than a dropdown.)

**Comment by kristofa** [comment]
Thanks for letting me know. I'll verify this soon and try to get a bugfix release out soon.

**Comment by kristofa** [comment]
I submitted a new version (1.2) which includes a fix for this bug to the App Store for review. I expect it to become available in the next days. 

I didn't include changing the dropdown list into a checkbox but I agree this would be nicer (also from a code point of view). I'll make a separate issue to update this later.
