### ISSUE TITLE
Text field focus should default to Title or Tags

### ISSUE THREAD

**Issue by roosterboy** [kristofa/bookmarker_for_pinboard#9]
The extension popover in Safari should default to having text field focus in either the Title or Tags field instead of the URL field. Users are far more likely to want to edit the title or add tags before saving a bookmark to Pinboard than they are to change the URL. Considering they are bookmarking the URL, chances are that field will almost never be changed, though there are circumstances when it might be.

<img width="345" alt="Screen Shot 2019-03-09 at 14 01 54" src="https://user-images.githubusercontent.com/5996293/54077912-3d15f700-4274-11e9-9da1-9ce05698a8aa.png">

**Comment by apas** [comment]
I vote for tags.

**Comment by kristofa** [comment]
Thanks both @roosterboy and @apas. I like the suggestion and will look into this soon. My preference would also be to focus in the 'Tags' text field.

**Comment by kristofa** [comment]
I submitted a new version (1.2) which includes this improvement to the App Store for review. I expect it to become available in the next days.
